server:
  tomcat:
    accesslog:
      prefix: access_log
      enabled: 'true'
      suffix: log
      rename-on-rotate: 'true'
  spring:
    datasource:
      driver-class-name: ${DRIVER_CLASS_NAME}
      url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
fine_tuned_model_id: ${MODEL_ID}
client: ${MODEL_CLIENT}
