server:
  tomcat:
    accesslog:
      prefix: access_log
      enabled: 'true'
      suffix: log
      rename-on-rotate: 'true'
  spring:
    datasource:
      url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false
      username: ${DB_USER_NAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
fine_tuned_model_id: ${MODEL_ID}
client: ${MODEL_CLINET}
