spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.SQL: debug

server:
  port: 8080

fine_tuned_model_id: ${MODEL_ID}
client: ${MODEL_CLIENT}